### ISSUE TITLE
cannot be installed via Composer

### ISSUE THREAD

**Issue by pixeline** [taufik-nurrohman/parsedown-extra-plugin#16]
AFAICS, `composer require taufik-nurrohman/parsedown-extra-plugin` does not work, even with `minimum-stability`set to `dev`.

Returned message:

```
 [InvalidArgumentException]                                                                                                                          
  Could not find a matching version of package taufik-nurrohman/parsedown-extra-plugin. Check the package spelling, your version constraint and that  
   the package is available in a stability which matches your minimum-stability (dev).        
``` 

[This could help](https://stackoverflow.com/questions/47050781/composer-require-could-not-find-package).

**Comment by taufik-nurrohman** [comment]
Will fix this after #15, thanks!

**Comment by pixeline** [comment]
> Will fix this after #15, thanks! So, as long as it set as a stable version, this error will dissapears right?

Well I don't think so. According to [this](https://stackoverflow.com/a/49029744/53960), the issue is how you tag your releases. Composer needs strict versioning like: `0.0.1` you have added "beta" and other unrecognized characters in it.

**Comment by pixeline** [comment]
ah but I see you released a properly named version 2 days ago. Let me try!

**Comment by pixeline** [comment]
Still same error message.

` composer require taufik-nurrohman/parsedown-extra-plugin
`
```
                                                                                                                                                              
  [InvalidArgumentException]                                                                                                                                  
  Could not find a matching version of package taufik-nurrohman/parsedown-extra-plugin. Check the package spelling, your version constraint and that the pac  
  kage is available in a stability which matches your minimum-stability (stable).                                                                             
                                                                                                                                                              
```

**Comment by pixeline** [comment]
also: i don't actually see your package on https://packagist.org/?query=taufik-nurrohman you probably need to submit it: https://packagist.org/packages/submit

**Comment by taufik-nurrohman** [comment]
@pixeline Maybe because this account name previously was `@tovic`.

**Comment by taufik-nurrohman** [comment]
Could you help me to sync this repository with yours? So everything will be up-to-date.

https://packagist.org/packages/taufik-nurrohman/parsedown-extra-plugin

**Comment by jaroslavlibal** [comment]
@pixeline Could you please change the canonical URL to the original repository instead of your fork and make @taufik-nurrohman a (co)maintainer or rename/delete your packagist package (named as the original repository), please? This situation is quite confusing for users as the installed library is not the same as expected.

I don't think this solution is the best one. Thanks!

**Comment by pixeline** [comment]
> @pixeline Could you please change the canonical URL to the original repository instead of your fork and make @taufik-nurrohman a (co)maintainer or rename/delete your packagist package (named as the original repository), please? This situation is quite confusing for users as the installed library is not the expected one.
> 
> I don't think this solution is the best one. Thanks!

it should be done, now. Is that correct ?

**Comment by taufik-nurrohman** [comment]
Thanks!

**Comment by jaroslavlibal** [comment]
Thank you guys! We'll probably have to explicitly require `"erusev/parsedown": "@dev"` in our projects with the 1.3.2 version released a few minutes ago, but everything works now, thanks again!

**Comment by taufik-nurrohman** [comment]
@jaroslavlibal I will consider to update it when I have the time.
