### ISSUE TITLE
Parsing stalls and then fails when string ends in '!'

### ISSUE THREAD

**Issue by daydreamjesse** [taufik-nurrohman/parsedown-extra-plugin#17]
Hey there, I've come across an issue when using exclamation points in .md files. I understand that '!' is an identifier for images, but it should be able to recognize when it's not being used for that purpose, yeah?

I'm making a markdown editor for our work's knowledge base and so far this has worked flawlessly, so credit where it's due for sure. But whenever I use an exclamation point in a context that isn't with an ![Image] tag, it takes the page about two minutes to load and then PHP fails after the parser function is called.

Here's a sample of a .md that I parse into a string:
```
# I am using this page for Markdown Testing
**Please do not remove this page**
***

## To-Do
- ~~Add sticky buttons for _italics_, __bold__, etc.~~
- ~~Include image upload~~
- ~~Include way to hyperlink to other parts of PHD: almost done~~
- Include way to add sections of pages with MD editor 
Test!
```

The above provides the following after about two minutes:
![ex1](https://user-images.githubusercontent.com/18193667/76652258-37f92100-6534-11ea-8537-ef1cadcdc38b.PNG)

If I remove 'Test!' it looks like this(load time about 400ms):
![ex2](https://user-images.githubusercontent.com/18193667/76652286-45aea680-6534-11ea-902e-c9819bbe6cd2.PNG)

And here's proof that images work as intended:
![ex3](https://user-images.githubusercontent.com/18193667/76652302-4d6e4b00-6534-11ea-9231-1a8133866693.PNG)

If you need any more info about my project/code structure, let me know and I'll provide it.

**Comment by taufik-nurrohman** [comment]
What version are you using? Current `ParsedownExtraPlugin` extension is 1.2.0. I seem to have experienced this issue before, it&rsquo;s just that I forgot where.

**Comment by taufik-nurrohman** [comment]
https://github.com/erusev/parsedown/issues/546

**Comment by daydreamjesse** [comment]
Yes, I was using an older version, got it updated 👍
