### ISSUE TITLE
data-* attributes aren't copied to parent

### ISSUE THREAD

**Issue by bricebou** [taufik-nurrohman/parsedown-extra-plugin#26]
When I do:

~~~ markdown
``` {.language-shell .command-line data-output=2-20}
~~~

only classes are reported to the `<pre>` parent element even with

~~~ php
$Parsedown->codeAttributesOnParent = true;
~~~

Am I missing something?

**Comment by taufik-nurrohman** [comment]
Try:

~~~ php
$Parsedown->codeAttributesOnParent = ['class', 'data-output', 'id'];
~~~

**Comment by bricebou** [comment]
Yeah, that works great ! Is it possible to use a regular expression to replicate all data attributes ? Something like data-* ?

I was wondering also why there is $blockCodeClassFormat which permits to add "language-" while we find the blockFencedCode function in Parsedown which does the same ?

Thanks again and in advance :)

**Comment by taufik-nurrohman** [comment]
> Is it possible to use a regular expression to replicate all data attributes ?

It is not possible for simplicity and maybe security too.

> I was wondering also why there is `$blockCodeClassFormat` which permits to add `language-`

It was for the class name dot prefix behavior in my extension. See the feature about automatic `language-` prefix in code block.

**Comment by bricebou** [comment]
> It is not possible for simplicity and maybe security too.

Yeah, seems logic :)
 
> It was for the class name dot prefix behavior in my extension. See the feature about automatic `language-` prefix in code block.

I understand the logic but I've got this : language-language-class while doing this:

```
```shell
```

I I do that:
```
```{shell .command-line data-output="2-20"}
```

I get `<pre class="command-line" data-output="2-20"><code shell="shell">`.

I try this:

```
```shell {.command-line data-output="2-20"}
```

And I get `<pre class="command-line" data-output="2-20"><code>`...

What am I missing ?

**Comment by taufik-nurrohman** [comment]
> I understand the logic but I've got this `language-language-class`

Looks like a bug to me.

For the second example, think of any characters between `{` and `}` as literal HTML attributes. It just that `.foo` and `#foo` is special here. In general, you can do `foo="bar"`, `foo='bar'` and `foo=bar`. When you see attribute without value, it will be parsed to `attribute="attribute"` in the output.

Think of `shell` in `{shell foo="bar"}` as `disabled` and `readonly` in `<input disabled readonly foo="bar">`.

**Comment by taufik-nurrohman** [comment]
What happen if you do this?

~~~ markdown
``` {class="shell" data-output="2-20"}
~~~

**Comment by bricebou** [comment]
I get `<pre class="shell" data-output="2-20"><code>`.

**Comment by bricebou** [comment]
Is there a way to combine multiple attributes along with the auto prefix "language-" ?

Is there a way to get this

```html
<pre class="language-shell command-line" data-output="2-20"><code>
```

besides of 

```md
``` {class="language-shell command-line" data-output="2-20"}
```

Thanks again !

**Comment by taufik-nurrohman** [comment]
I am afraid that this request will expand to other valid elements that has advance attribute features. You don&rsquo;t want to have a heading tag with class names that automatically be prefixed by `language-`.

``` markdown
### Test {.foo}
```

Expect `<h3 class="foo">` but get `<h3 class="language-foo">`.

**Comment by bricebou** [comment]
Right !

Anyway, maybe ParsedownExtraPlugin should test if there is a space between the code block tag ` ``` ` and the class:

```md
```html
```
is already parsed by Parsedown as 
```html
<pre><code class="language-html">
```
ParsedownExtraPlugin should add 'language-' only when we have:

```md
``` html
```

No ?

**Comment by bricebou** [comment]
Hum... Parsedown adds also "language-" when parsing :

```md
``` html
```

**Comment by bricebou** [comment]
Tanks !
